# Generated by Django 4.2 on 2023-12-28 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacc_perc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CovidStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_id', models.DateField()),
                ('positive', models.IntegerField(blank=True)),
                ('mortality', models.IntegerField(blank=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RESTAPI.phase')),
                ('vacc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RESTAPI.vaccination')),
            ],
        ),
    ]
