# Generated by Django 5.0 on 2024-01-01 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalised', models.IntegerField(blank=True)),
                ('icu', models.IntegerField(blank=True)),
                ('oxygen_unstable', models.IntegerField(blank=True)),
                ('discharged', models.IntegerField(blank=True)),
                ('isolation', models.IntegerField(blank=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RESTAPI.covidstats')),
            ],
        ),
    ]
