# Generated by Django 5.0 on 2024-01-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0004_alter_vaccination_vacc_perc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='vacc_perc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
