# Generated by Django 5.0 on 2024-01-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0009_alter_covidstats_phase_alter_covidstats_vacc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidstats',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='covidstats',
            name='vacc',
        ),
    ]
