# Generated by Django 5.0 on 2024-01-01 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0011_covidstats_phase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidstats',
            name='vacc',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='RESTAPI.vaccination'),
            preserve_default=False,
        ),
    ]
