# Generated by Django 5.0 on 2024-01-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0012_covidstats_vacc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='vacc_perc',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
