# Generated by Django 5.0 on 2024-01-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0015_rename_phase_id_covidstats_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidstats',
            name='id',
        ),
        migrations.AlterField(
            model_name='covidstats',
            name='date_id',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
