# Generated by Django 5.0 on 2024-01-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0018_remove_vaccination_id_alter_vaccination_vacc_perc'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='vacc_perc',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
