# Generated by Django 5.0 on 2024-01-02 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0016_remove_covidstats_id_alter_covidstats_date_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalisation',
            name='id',
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='date',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='RESTAPI.covidstats'),
        ),
    ]
