# Generated by Django 5.0 on 2024-01-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RESTAPI', '0017_remove_hospitalisation_id_alter_hospitalisation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='id',
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='vacc_perc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
